### PR TITLE
fix: allow disabling `markdown-it-attrs`

### LINKED ISSUE #629: break with `{String|RegExp|Object|Function}`
### Describe the bug

```bash
$ npm run docs:dev
```

when `README.md` includes some string like `{String|RegExp|Object|Function}`

got error:

```bash
DOMException: Failed to execute 'setAttribute' on 'Element': 'String|RegExp|Object|Function' is not a valid attribute name.
```

### Reproduction

```markdown
### wait(type, expected)

Wait for your expectations to pass. It's useful for testing long-run apps such as build tools or http servers.

- `type`: {String} - support `message` / `stdout` / `stderr` / `close`
- `expected`: {String|RegExp|Object|Function}
```

### Expected behavior

work fine.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 63.44 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/1367_1652147272868/bin/node
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/1367_1652147272868/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
```

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### LINKED ISSUE #662: Add an option to disable `markdown-it-attrs` plugin
See #629

```js
export default {
  markdown: {
    // Pass `false` to disable this plugin.
    attrs: false
  }
}
```

### PR DESCRIPTION
**Pull request by brc-dd**
fixes #662
fixes #629

`markdown-it-attrs` can now be disabled using the following config:

```ts
import { defineConfig } from 'vitepress'

export default defineConfig({
  markdown: { attrs: { disable: true } },
})
```

### CODE REVIEW

**Review by kiaking — APPROVED** [review]
Wonderful job, as always! 🚀

File: src/node/markdown/plugins/highlightLines.ts [hunk 1]
```diff
@@ -9,16 +10,34 @@ export const highlightLinePlugin = (md: MarkdownIt) => {
...
+      const rawInfo = token.info
+
+      if (!rawInfo || !RE.test(rawInfo)) {
+        return fence(...args)
+      }
+
+      const langName = rawInfo.replace(RE, '').trim()
+
+      // ensure the next plugin get the correct lang
+      token.info = langName
```
Comment (JounQin) [inline src/node/markdown/plugins/highlightLines.ts:30]: @brc-dd Should this plugin be used after `attrs`? It changes `token.info`, `attrs` seems not working to me.

image

image

Comment (brc-dd) [reply src/node/markdown/plugins/highlightLines.ts:30]: This wasn't working on v0 too IG. Can you create a separate issue for this? Probably the attributes on `code` are getting removed somewhere.

Comment (JounQin) [reply src/node/markdown/plugins/highlightLines.ts:30]: @brc-dd Done #826
