### PR TITLE
fix(ally): clear up confusion with the title of theme switch

### LINKED ISSUE #3214: Theme: the title of theme switch
### Describe the bug

Currently, the title of the theme switch is `toggle dark mode` whether in light mode or dark mode.
image

image

### Reproduction

https://vitepress.dev/guide/getting-started

### Expected behavior

In light mode, the title should be `toggle dark mode`; in dark mode, the title should be `toggle light mode`

### System Info

```Text
Both in Mac or Windows
```

### Additional context

_No response_

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by zh-lx**
fix #3214

### CODE REVIEW

**Comment by brc-dd** [comment]
Ah, this is bit subjective, but when we write "toggle dark mode", we mean toggle the state of dark mode to its opposite. It's different from "toggle to dark mode". In that case you suggestion would've made sense. We can make it something like "Switch to light theme"/"Switch to dark theme" instead if the current title is bit confusing.

File: src/client/theme-default/components/VPSwitchAppearance.vue [hunk 1]
```diff
@@ -10,11 +10,15 @@ const { isDark } = useData()
 const toggleAppearance = inject('toggle-appearance', () => {
   isDark.value = !isDark.value
 })
+
+const switchTitle = computed(() => {
+  return isDark.value ? 'toggle light mode' : 'toggle dark mode'
```
Comment (brc-dd) [inline src/client/theme-default/components/VPSwitchAppearance.vue:15]:
```suggestion
  return isDark.value ? 'Switch to light mode' : 'Switch to dark mode'
```

File: src/client/theme-default/components/VPSwitchAppearance.vue [hunk 2]
```diff
@@ -10,11 +10,15 @@ const { isDark } = useData()
 const toggleAppearance = inject('toggle-appearance', () => {
   isDark.value = !isDark.value
 })
+
+const switchTitle = computed(() => {
+  return isDark.value ? 'Switch to light mode' : 'Switch to dark mode'
```
Comment (brc-dd) [inline src/client/theme-default/components/VPSwitchAppearance.vue:15]:
```suggestion
  return isDark.value ? 'Switch to light theme' : 'Switch to dark theme'
```
