### PR TITLE
fix: compatible with `--base` flag

### LINKED ISSUE #835: `vitepress build docs --base /xxx/` does not work as expected
### Describe the bug

It is passed as `build.base` instead of root level `base` option

```log
"build.base" option is deprecated. "base" is now a root-level config option.
```

### Reproduction

N/A

### Expected behavior

No warning and work

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.91 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/Library/Caches/fnm_multishells/985_1655820447617/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/985_1655820447617/bin/yarn
    npm: 8.12.1 - ~/Library/Caches/fnm_multishells/985_1655820447617/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
    Safari: 16.0
  npmPackages:
    vitepress: ^1.0.0-alpha.2 => 1.0.0-alpha.2
```

### Additional context

Working on a fix.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by JounQin**
close #835

### CODE REVIEW

**Comment by brc-dd** [comment]
`vitepress serve` will break in this case. It requires the base to be in site config itself.

**Comment by JounQin** [comment]
> `vitepress serve` will break in this case. It requires the base to be in site config itself.

@brc-dd 

So we should support `vitepress serve --base /xxx/`?

**Comment by brc-dd** [comment]
We can, but I don't feel any need to introduce support for this. We'll need to change this:

https://github.com/vuejs/vitepress/blob/baf8083e668ce50a9d26d9398609e196237ebc95/src/node/serve/serve.ts#L26

to this:

```ts
  const base = trimChar(options.base ?? site?.site?.base ?? '', '/')
```

Then:

```sh
pnpm docs-build-only -- --base /foo/
pnpm docs-serve -- --base /foo/
```

will work.

**Comment by JounQin** [comment]
@brc-dd Done!

File: src/node/build/build.ts [hunk 1]
```diff
@@ -9,14 +9,14 @@ import { bundle, okMark, failMark } from './bundle'
 
 export async function build(
   root: string,
-  buildOptions: BuildOptions & { base?: string; mpa?: string } = {}
```
Comment (JounQin) [inline src/node/build/build.ts]: There is no `base` available in `BuildOptions` because it is deprecated.

**Comment by brc-dd** [comment]
Should we support this in dev too?

**Comment by JounQin** [comment]
> Should we support this in dev too?

It seems vite does support this, but this is uncommon usage for myself.

File: src/node/server.ts [hunk 2]
```diff
@@ -10,7 +10,7 @@ export async function createServer(
 
   return createViteServer({
     root: config.srcDir,
-    base: config.site.base,
+    base: serverOptions.base ?? config.site.base,
```
Comment (brc-dd) [inline src/node/server.ts:13]: Yeah, this won't work, because the rest of VitePress needs it to be in site config itself. This option is to pass that to Vite only.

Comment (JounQin) [reply src/node/server.ts]: Changed as your suggestion.

**Review by brc-dd — APPROVED** [review]
