### PR TITLE
fix(theme): set search box min-width for >=751px

### LINKED ISSUE #250: Algolia search field collapse behaviour
**Describe the bug**
Between screen sizes `720px` and `751px`, the search field is collapsed, but still takes up the space of the expanded version:

Screenshot of VitePress homepage

This issue seems to be baked into the VitePress default theme.

**To Reproduce**
1. Open a device with screen width larger than `800px` (laptop or desktop).
2. Visit any VitePress site (example: https://vitepress.vuejs.org).
3. Slowly resize the browser window, paying special attention when getting to the `751px` threshold.
4. Done.

**Expected behavior**

The search field should only collapse at screen sizes smaller than `720px`.

**System Info**
- vitepress version: 0.12.2
- vite version: unknown for https://vitepress.vuejs.org, `2.0.3` for local reproduction.
- Node version: unknown for https://vitepress.vuejs.org, `15.10.0` for local reproduction.
- OS version: unknown for https://vitepress.vuejs.org, MacOS 11.1 for local reproduction.

**Additional context**

From https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/components/AlgoliaSearchBox.vue:
``` js
@media (min-width: 720px) {
  .algolia-search-box {
    padding-left: 8px;
    min-width: 176.3px; /* avoid layout shift */
  }
}
@media (min-width: 751px) {
  .algolia-search-box {
    padding-left: 8px;
  }
  .algolia-search-box .DocSearch-Button-Placeholder {
    padding-left: 8px;
    font-size: 0.9rem;
    font-weight: 500;
  }
}
```

I still don't quite understand the purpose of the `@media (min-width: 751px) {...}`, since in other default theme components, the screen width breakpoint is at `720px`, but it seems to me that combining the two media queries should solve the problem.

Another solution might be to simply move the `min-width: 176.3px;` under the `@media (min-width: 751px) {...)` section.

### PR DESCRIPTION
**Pull request by dnischeta**
### Description

This PR closes #250.

### Solution

```min-width: 176,3px``` was moved to ```@media (min-width: 751px) { ... }``` block (as @nico-bachner suggested in issue).

### Result
- 751px

- 750px

- 720px

### CODE REVIEW

File: src/client/theme-default/components/AlgoliaSearchBox.vue [hunk 1]
```diff
@@ -139,12 +139,12 @@ function initialize(userOptions: any) {
...
   .algolia-search-box {
     padding-left: 8px;
-    min-width: 176.3px; /* avoid layout shift */
   }
 }
 
 @media (min-width: 751px) {
   .algolia-search-box {
+    min-width: 176.3px; /* avoid layout shift */
     padding-left: 8px;
```
Comment (dnischeta) [inline src/client/theme-default/components/AlgoliaSearchBox.vue:148]: Maybe it is worth to remove ```padding-left: 8px``` from this rules block. This rule is already set in ```@media (min-width: 720px) { ... }``` block.

**Comment by dnischeta** [comment]
Maybe it is worth to remove ```padding-left: 8px``` from ```@media (min-width: 720px) { ... }``` rules block. This rule is already set in ```@media (min-width: 720px) { ... }``` block.

```css
@media (min-width: 720px) {
  .algolia-search-box {
    padding-left: 8px;
  }
}
@media (min-width: 751px) {
  .algolia-search-box {
    min-width: 176.3px; /* avoid layout shift */
    padding-left: 8px;
  }
  .algolia-search-box .DocSearch-Button-Placeholder {
    padding-left: 8px;
    font-size: 0.9rem;
    font-weight: 500;
  }
}
```

**Comment by nico-bachner** [comment]
Nice. Looks good.

To me it seems that
```css
@media (min-width: 751px) {
  .algolia-search-box {
    padding-left: 8px;
  }
}
```
is indeed superfluous as you say. Not sure if I'm missing anything though.

**Comment by dnischeta** [comment]
I removed rule repeat with last commit.
